language: python
python:
    - "2.7"
env:
    SECRET_KEY="Not secret"
install: pip install -r requirements.txt
addons:
    postgresql: "9.2"
before_script:
    - psql -c 'create database blogful_test;' -U postgres
script:
    - PYTHONPATH=. python tests/test_filter.py
    - PYTHONPATH=. python tests/test_views_integration.py
    - PYTHONPATH=. python tests/test_views_acceptance.py
