language: python
python:
    - "2.7"
install: pip install -r requirements.txt
script:
    - PYTHONPATH=. python blog/tests/test_filters.py
    - PYTHONPATH=. python blog/tests/test_views_integration.py
    - PYTHONPATH=. python blog/tests/test_views_acceptance.py
